### GET /streaming/account/{{newAccountId}}/full
GET {{host}}/streaming/account/{{newAccountId}}/full
Host: streaming.bose.com
Authorization: Bearer {{authToken}}
Content-Type: application/vnd.bose.streaming-v1.2+xml
User-Agent: Bose_Lisa/27.0.6
Accept: application/vnd.bose.streaming-v1.2+xml

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
        client.assert(response.contentType.mimeType === "application/vnd.bose.streaming-v1.2+xml", "Expected 'application/vnd.bose.streaming-v1.2+xml' but received '" + response.contentType.mimeType + "'");
    });

    client.test("Response body contains <account>", function() {
        const expectedAccountId = client.global.get("newAccountId") || client.variables.environment.get("accountId");
        const doc = response.body;
        const account = doc.getElementsByTagName("account")[0];
        client.assert(account !== undefined, "Response body does not contain <account>");
        client.assert(account.getAttribute("id") === expectedAccountId, "Expected account id '" + expectedAccountId + "' but received '" + account.getAttribute("id") + "'");
    });
%}
