### GET /streaming/account/{{newAccountId}}/device/{{deviceId}}/group/
GET {{host}}/streaming/account/{{newAccountId}}/device/{{deviceId}}/group/
Host: streaming.bose.com
Content-Type: application/vnd.bose.streaming-v1.2+xml
User-Agent: Bose_Lisa/27.0.6
Accept: application/vnd.bose.streaming-v1.2+xml
Authorization: Bearer {{authToken}}

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
        client.assert(response.contentType.mimeType === "application/vnd.bose.streaming-v1.2+xml", "Expected 'application/vnd.bose.streaming-v1.2+xml' but received '" + response.contentType.mimeType + "'");
    });

    client.test("Response body contains <group/>", function() {
        const doc = response.body;
        client.assert(doc.getElementsByTagName("group").length > 0, "Response body does not contain <group/>");
    });
%}
